from jinja2 import Environment, BaseLoader
from datetime import datetime
from plant_reliability.core.validation.data_quality import DataQualityReport
from plant_reliability.analysis.bad_actors.engine import BadActorScore
from plant_reliability.core.metrics.definitions import (
    calculate_mtbf,
    calculate_mttr,
    calculate_availability,
)
from plant_reliability.core.timeline.reconstruction import AssetTimeline
from typing import List, Dict

# Very simple template directly in code for offline-first zero-config packaging
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Plant Reliability Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 2rem; }
        h1, h2, h3 { color: #2c3e50; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 2rem; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .issue-warning { color: #856404; background-color: #fff3cd; padding: 10px; border-left: 5px solid #ffeeba; margin-bottom: 10px;}
        .issue-error { color: #721c24; background-color: #f8d7da; padding: 10px; border-left: 5px solid #f5c6cb; margin-bottom: 10px;}
        .metric-card { border: 1px solid #eee; padding: 15px; border-radius: 5px; margin-bottom: 15px; background: #fafafa;}
    </style>
</head>
<body>
    <h1>Plant Reliability Report</h1>
    <p><strong>Generated on:</strong> {{ generated_at }}</p>
    
    <h2>1. Data Quality Assessment</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Rows Imported</td><td>{{ dq.rows_imported }}</td></tr>
        <tr><td>Valid Records</td><td>{{ dq.valid_records }}</td></tr>
        <tr><td>Timestamp Completeness</td><td>{{ "%.1f"|format(dq.timestamp_completeness) }}%</td></tr>
        <tr><td>Asset ID Completeness</td><td>{{ "%.1f"|format(dq.asset_id_completeness) }}%</td></tr>
    </table>
    
    {% if dq.issues %}
    <h3>Identified Issues</h3>
    {% for issue in dq.issues %}
        <div class="issue-{{ issue.severity.value | lower }}">
            <strong>{{ issue.severity.value }}</strong>: {{ issue.description }}<br>
            <small>Recommendation: {{ issue.remediation }}</small>
        </div>
    {% endfor %}
    {% endif %}

    <h2>2. Bad Actors (Top 10)</h2>
    <table>
        <tr>
            <th>Asset ID</th>
            <th>Composite Score</th>
            <th>Failures</th>
            <th>Downtime (h)</th>
            <th>Cost</th>
        </tr>
        {% for actor in bad_actors %}
        <tr>
            <td><strong>{{ actor.asset_id }}</strong></td>
            <td>{{ "%.2f"|format(actor.composite_score) }}</td>
            <td>{{ actor.failure_frequency }}</td>
            <td>{{ "%.1f"|format(actor.downtime_hours) }}</td>
            <td>${{ "%.2f"|format(actor.maintenance_cost) }}</td>
        </tr>
        {% endfor %}
    </table>

    <h2>3. Reliability Metrics (Top 5 Bad Actors)</h2>
    {% for res in metrics %}
    <div class="metric-card">
        <h3>{{ res.asset_id }}</h3>
        <p><strong>MTBF:</strong> {{ "%.1f"|format(res.mtbf) }} h</p>
        <p><strong>MTTR:</strong> {{ "%.1f"|format(res.mttr) }} h</p>
        <p><strong>Availability:</strong> {{ "%.2f"|format(res.availability) }}%</p>
    </div>
    {% endfor %}
    
    <hr>
    <p><small>Generated by plant-reliability - Auditable Reliability Engineering Software</small></p>
</body>
</html>
"""


def generate_html_report(
    dq_report: DataQualityReport,
    bad_actors: List[BadActorScore],
    timelines: Dict[str, AssetTimeline],
    events: List,
    output_path: str,
):
    env = Environment(loader=BaseLoader())
    template = env.from_string(HTML_TEMPLATE)

    metrics = []
    # Just show metrics for top 5 bad actors
    for actor in bad_actors[:5]:
        tl = timelines.get(actor.asset_id)
        if tl:
            mtbf = calculate_mtbf(tl, events)
            mttr = calculate_mttr(events, actor.asset_id)
            avail = calculate_availability(tl)
            metrics.append(
                {
                    "asset_id": actor.asset_id,
                    "mtbf": mtbf.value,
                    "mttr": mttr.value,
                    "availability": avail.value,
                }
            )

    html_content = template.render(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        dq=dq_report,
        bad_actors=bad_actors[:10],
        metrics=metrics,
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return output_path
